#!/usr/bin/env python

# Copyright (c) 2017 Computer Vision Center (CVC) at the Universitat Autonoma de
# Barcelona (UAB).
#
# This work is licensed under the terms of the MIT license.
# For a copy, see <https://opensource.org/licenses/MIT>.

import glob
import os
import sys

try:
    sys.path.append(glob.glob('**/*%d.%d-%s.egg' % (
        sys.version_info.major,
        sys.version_info.minor,
        'win-amd64' if os.name == 'nt' else 'linux-x86_64'))[0])
except IndexError:
    pass

import carla
import pygame
import random
import time
import numpy as np

def main():
    actor_list = []

    # In this tutorial script, we are going to add a vehicle to the simulation
    # and let it drive in autopilot. We will also create a camera attached to
    # that vehicle, and save all the images generated by the camera to disk.

    try:
        # First of all, we need to create the client that will send the requests
        # to the simulator. Here we'll assume the simulator is accepting
        # requests in the localhost at port 2000.

        port = 2000
        client = carla.Client('localhost', port)
        client.set_timeout(2.0)

        # Once we have a client we can retrieve the world that is currently
        # running.
        world = client.get_world()

        # The world contains the list blueprints that we can use for adding new
        # actors into the simulation.
        blueprint_library = world.get_blueprint_library()

        # Now let's filter all the blueprints of type 'vehicle' and choose one
        # at random.
        bp = random.choice(blueprint_library.filter('vehicle'))

        # A blueprint contains the list of attributes that define a vehicle
        # instance, we can read them and modify some of them. For instance,
        # let's randomize its color.
#         color = random.choice(bp.get_attribute('color').recommended_values)
  #       bp.set_attribute('color', color)

        # Now we need to give an initial transform to the vehicle. We choose a
        # random transform from the list of recommended spawn points of the map.
        transform = random.choice(world.get_map().get_spawn_points())

        # So let's tell the world to spawn the vehicle.
        vehicle = world.spawn_actor(bp, transform)

        # It is important to note that the actors we create won't be destroyed
        # unless we call their "destroy" function. If we fail to call "destroy"
        # they will stay in the simulation even after we quit the Python script.
        # For that reason, we are storing all the actors we create so we can
        # destroy them afterwards.
        actor_list.append(vehicle)
        print('created %s' % vehicle.type_id)

        # Let's put the vehicle to drive around.
        vehicle.set_autopilot(True)

        # Let's add now a "depth" camera attached to the vehicle. Note that the
        # transform we give here is now relative to the vehicle.
        camera_bp = blueprint_library.find('sensor.camera.depth')
        camera_transform = carla.Transform(carla.Location(x=1.5, z=2.4))
        camera = world.spawn_actor(camera_bp, camera_transform, attach_to=vehicle)
        actor_list.append(camera)
        print('created %s' % camera.type_id)

        cc = carla.ColorConverter.LogarithmicDepth
        # add lane invasion sensors
        bp = world.get_blueprint_library().find('sensor.other.lane_detector')
        invasion_sensor = world.spawn_actor(bp, carla.Transform(), attach_to=vehicle)
        invasion_sensor.listen(lambda event: _parse_invasion(event))
        actor_list.append(invasion_sensor)
        # camera.listen(lambda image: _parse_image(image, cc))



        map = world.get_map()
        waypoint = map.get_waypoint(vehicle.get_location())
        waypoint = random.choice(waypoint.next(12.0))
        print(waypoint.transform)


        time.sleep(2)

    finally:

        # print('destroying actors')
        for actor in actor_list:
            # print(actor)
            actor.destroy()
        # print('done.')


def _parse_image(image, cc):
        image.convert(cc)
        array = np.frombuffer(image.raw_data, dtype=np.dtype("uint8"))
        array = np.reshape(array, (image.height, image.width, 4))

        array = array[:, :, -2:-5:-1]

        # surface = pygame.surfarray.make_surface(array.swapaxes(0, 1))
        # print(array.shape)
        print("vnao;inrv;oanerovnoevnoae;vno;vn")
#
def _parse_invasion(event):
    text = ['%r' % str(x).split()[-1] for x in set(event.crossed_lane_markings)]


if __name__ == '__main__':
    main()
